### ISSUE TITLE
newpage sometimes crashes plantuml/vscode plugin

### ISSUE THREAD

**Issue by danielsoriano** [qjebbs/vscode-plantuml#171] opened 2018-11-13 17:59 UTC
The use of "newpage" on sequence diagrams sometimes crashes the plugin so that it stops refreshing the diagrams. Even clicking on "Preview Current Diagram" does not work. 

The only workaround is to stop using the "newpage" keyword, or at least comment it until yoou need to export the diagram.

**Comment by danielsoriano** [comment] 2018-11-13 18:03
Using PlantUML plugin version 2.9.9 on Visual Studio Code 1.29.0 (user setup). 

Visual Studio Code About text:
Version: 1.29.0 (user setup)
Commit: 5f24c93878bd4bc645a4a17c620e2487b11005f9
Date: 2018-11-12T07:47:15.448Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Java SE 1.8.0_191 x64

PLANTUML_LIMIT_SIZE=65536

**Comment by qjebbs** [comment] 2018-11-14 04:35
cannot reproduce here, can you send me the plantuml source code?

**Comment by qjebbs** [comment] 2018-12-22 04:02
closing due to no more feedback..

**Closed by qjebbs** 2018-12-22 04:02 UTC
