### ISSUE TITLE
Failing to preview diagram (Alt + D) [VSCode 1.27.2]

### ISSUE THREAD

**Issue by pikenikes** [qjebbs/vscode-plantuml#153] opened 2018-10-05 19:02 UTC
Hi,

Preview diagram is failing on VSCode 1.27.2, it reports me the following error: Unable to open 'PlantUML Preview': resource is not available.

I've been digging about this (originally I though this was some bad configuration), but then I stumbled upon this [comment](https://github.com/Microsoft/vscode/issues/52246#issuecomment-406006385) stating that `vscode.previewHtml` is deprecated. So, I decided to take a look on extensions' source code and found [this](https://github.com/qjebbs/vscode-plantuml/blob/master/src/providers/previewer.ts#L216). I tried to debug this to confirm this is what's really causing the issue, but I'm a complete JS noob and couldn't get to debug anything 😄 (.NET is my world 😉 )

Can you please tell if this is really an issue? 

Thanks for your attention! 🙂

**Comment by heraclitusq** [comment] 2018-10-06 04:06
Encountered the similar issue today (not sure if it's the same cause).
VSC version 1.27.2 on MacOS 10.13.6.
PlantUML plugin version: 2.9.3
Java version: 1.8.0_181-b13

prompt: `Unable to open 'PlantUML Preview': resource is not available.`

The export function doesn't work either. not sure if it is related. The output:
```
TypeError: Cannot read property 'uri' of undefined
	at Config.exportOutDir (/Users/heraclitusq/.vscode/extensions/jebbs.plantuml-2.9.3/out/src/plantuml/config.js:66:72)
	at Object.calculateExportPath (/Users/heraclitusq/.vscode/extensions/jebbs.plantuml-2.9.3/out/src/plantuml/tools.js:99:34)
	at promises.push.diagrams.reduce (/Users/heraclitusq/.vscode/extensions/jebbs.plantuml-2.9.3/out/src/plantuml/exporter/exportDiagrams.js:79:36)
	at Array.reduce (<anonymous>)
	at doExportsLimited (/Users/heraclitusq/.vscode/extensions/jebbs.plantuml-2.9.3/out/src/plantuml/exporter/exportDiagrams.js:72:32)
	at Object.exportDiagrams (/Users/heraclitusq/.vscode/extensions/jebbs.plantuml-2.9.3/out/src/plantuml/exporter/exportDiagrams.js:19:16)
	at Object.<anonymous> (/Users/heraclitusq/.vscode/extensions/jebbs.plantuml-2.9.3/out/src/plantuml/exporter/exportDocument.js:56:26)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/heraclitusq/.vscode/extensions/jebbs.plantuml-2.9.3/out/src/plantuml/exporter/exportDocument.js:4:58)
	at <anonymous>
```

tried specifying java and plantuml.jar location, reinstall graphviz, doesn't help.

The command `java -jar plantuml.jar test.wsd` in the terminal works. (with the latest version of plantuml.jar downloaded from plantuml.com)

Thanks.

**Comment by qjebbs** [comment] 2018-10-06 11:29
`resource is not available` should've fixed with 2.9.4, I will switch to `webview` later..

**Comment by pikenikes** [comment] 2018-10-06 11:38
@qjebbs what a life saver! It got fixed indeed. Thanks for your help!

**Comment by heraclitusq** [comment] 2018-10-06 11:48
Just updated to v2.9.4. The issue is gone, and the export function works as well.
Thank you @qjebbs

**Comment by zoulja** [comment] 2018-10-06 12:34
2.9.4. helped, thanks a lot

**Comment by qjebbs** [comment] 2018-10-06 12:35
Sorry, it's my bad again..

**Closed by qjebbs** 2018-10-06 12:35 UTC
