### ISSUE TITLE
Copy diagram to clipboard

### ISSUE THREAD

**Issue by eladeyal-intel** [qjebbs/vscode-plantuml#364] opened 2020-12-30 18:15 UTC
I wish there was an easy way to copy the diagram (from the preview windows) to clipboard so it can be pasted where needed.

**Comment by qjebbs** [comment] 2020-12-31 02:44
welcome PR

**Comment by visma-kimhjortholm** [comment] 2021-01-18 15:24
It's possible to pass diagram info in the URL, try  this example http://www.plantuml.com/plantuml/png/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

**Comment by fuhrmanator** [comment] 2021-04-07 16:02
Duplicate of #288 ?

**Closed** 2021-04-07 20:47 UTC
