### ISSUE TITLE
Export does not create files (local renderer)

### ISSUE THREAD

**Issue by t7ko** [qjebbs/vscode-plantuml#120] opened 2018-05-08 14:26 UTC
Hi.

I need an ability to export plantuml to png from VS Code.  Through local renderer.

I followed the docs and made sure that I have Java and Graphviz installed, and they are both listed in PATH.

When I run export command in VS code, it reports success, but there is no file at the path it lists in output.

I'm on Windows 10.

What's confusing is, Preview works.  But export does not.

Please help.

**Comment by qjebbs** [comment] 2018-05-09 04:46
cannot reproduce. can you write down steps?

**Comment by t7ko** [comment] 2018-05-09 05:33
Sorry for the trouble -- I've figured it out.  Turns out it creates `out/` folder at the top level of the project, and then the full path within that.  The path was so long that I did not even notice this `out` thing in the middle of it.

**Comment by qjebbs** [comment] 2018-05-09 10:27
Good to hear, closing..

**Closed by qjebbs** 2018-05-09 10:27 UTC
