### ISSUE TITLE
Alt-D not working

### ISSUE THREAD

**Issue by astodolski** [qjebbs/vscode-plantuml#91] opened 2018-01-12 16:37 UTC
Preview only works using Markdown Preview Enhanced.  Alt-D results in PlantUML Preview  -> No valid diagram found here.  Have to use an alternate means to render

**Comment by qjebbs** [comment] 2018-01-13 06:41
please make sure the diagram has `@startuml` and  `@enduml`, this the specification of PlantUML

**Comment by qjebbs** [comment] 2018-01-19 04:05
According to your feedback, it's not a bug of the plugin, it's designed according to the specification of PlantUML. That is why plugin report to you "No valid diagram found here".

The Plugin has publish & widely used for such a long time, it's impossible existing such a low level bug.

Since there's no more feedback for a week, I'm closing this issue. 

I hope @astodolski can change to injustice rating in vscode market place, before it cause misunderstandings to more users.

**Closed by qjebbs** 2018-01-19 04:05 UTC

**Comment by lakshmantgld** [comment] 2018-03-02 02:11
Nice work @qjebbs on creating this awesome plugin. I totally understand that we need to follow the **plantuml** format like starting the diagram with `@startuml` and end the code with `@enduml`. I have some old repositories which do not follow that rule.

So, is there any attribute that I can use, which don't expect the `@startuml` and `@enduml` in the `.puml` code. It would be great If I can do that. The diagrams that I am creating now enforce that rule, but the existing diagrams don't follow that. Right now, I am adding the startuml and enduml in the old diagrams to preview it, which is troublesome.

**Comment by dipakdotyadav** [comment] 2018-07-24 13:56
Alt+D opens "Debug menu" instead of digram preview. any help?

**Comment by qjebbs** [comment] 2018-07-24 14:00
@dipakdotyadav try change key bind settings?

**Comment by dipakdotyadav** [comment] 2018-07-24 14:13
@qjebbs Thanks it works, but now says "**No valid diagram found here**", tried with couple of file-extensions `.wsd` and `.puml`, with below content.

```
@startuml
title new page test
Alice -> Bob : test
@enduml
```

**Comment by qjebbs** [comment] 2018-07-26 03:07
@dipakdotyadav can you post steps to reproduce, works good here

**Comment by tjqiulu** [comment] 2018-09-27 09:12
@qjebbs 
I used VS code with plantuml, sequence diagram can display diagram, but other are not, we try to execute as the tip

\extensions\jebbs.plantuml-2.9.0  (plantuml@2.9.0)
λ ls -l
total 7266
-rw-r--r-- 1 Sep2885677   14234 Sep 27 14:28 CHANGELOG.md
-rw-r--r-- 1 Sep2885677    1082 Sep 27 14:28 LICENSE.txt
-rw-r--r-- 1 Sep2885677   11786 Sep 27 14:28 README.md
-rw-r--r-- 1 Sep2885677     459 Sep 27 14:28 build.js
drwxr-xr-x 1 Sep2885677       0 Sep 27 14:28 images/
drwxr-xr-x 1 Sep2885677       0 Sep 27 14:28 includes/
drwxr-xr-x 1 Sep2885677       0 Sep 27 14:28 langs/
-rw-r--r-- 1 Sep2885677     270 Sep 27 14:28 language-configuration.json
drwxr-xr-x 1 Sep2885677       0 Sep 27 14:28 node_modules/
drwxr-xr-x 1 Sep2885677       0 Sep 27 14:28 out/
-rw-r--r-- 1 Sep2885677  103049 Sep 27 14:28 package-lock.json
-rw-r--r-- 1 Sep2885677    8230 Sep 27 14:28 package.json
-rw-r--r-- 1 Sep2885677    3067 Sep 27 14:28 package.nls.de.json
-rw-r--r-- 1 Sep2885677    3780 Sep 27 14:28 package.nls.ja.json
-rw-r--r-- 1 Sep2885677    2787 Sep 27 14:28 package.nls.json
-rw-r--r-- 1 Sep2885677    2760 Sep 27 14:28 package.nls.zh-cn.json
-rw-r--r-- 1 Sep2885677    2699 Sep 27 14:28 package.nls.zh-tw.json
-rw-r--r-- 1 Sep2885677 7238820 Sep 27 14:28 plantuml.jar
drwxr-xr-x 1 Sep2885677       0 Sep 27 14:28 snippets/
drwxr-xr-x 1 Sep2885677       0 Sep 27 14:28 syntaxes/
drwxr-xr-x 1 Sep2885677       0 Sep 27 14:28 templates/

java -jar plantuml.jar -testdot
The environment variable GRAPHVIZ_DOT has not been set
Dot executable is null
Error: No dot executable found
Error: only sequence diagrams will be generated

**Comment by qjebbs** [comment] 2018-09-27 09:16
@tjqiulu See https://github.com/qjebbs/vscode-plantuml#requirements

**Comment by tjqiulu** [comment] 2018-09-27 09:37
> @tjqiulu See https://github.com/qjebbs/vscode-plantuml#requirements

Got! thanks

**Comment by eqhelm** [comment] 2026-06-03 08:35
And for anyone as stupid as me:
The cursor must be between @startuml and @enduml (or at least in the same line) when pressing ALT+D!
